version: "3"
services:
  nodeapp:
    container_name: blogs_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "5555:5555"
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017
    networks:
      - node-mongo-network
  mongodb:
    container_name: mongodb
    image: mongo:6.0
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=posts
    networks:
      - node-mongo-network
networks:
  node-mongo-network:
    driver: bridge